# Site Settings
title: "Sahi's Learning Blog"
email: mohamedfrancissahi@gmail.com
url: "https://sahi-mfg.github.io" # the base hostname & protocol for your site
github_username: sahi-mfg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Categories for the blog
collections:
  categories:
    output: true
    permalink: /:collection/:name/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Timezone
timezone: Africa/Abidjan

# Author information
author:
  name: Sahi Mohamed Francis Gonsangbeu


# Navigation
header_pages:
  - about.md
  - categories.md

# Social links
social_links:
  github: sahi-mfg
  linkedin: Sahi Mohamed Francis Gonsangbeu
